import type { Lead } from "@/lib/types";

export const mockLeads: Lead[] = [
  {
    id: "demo-1",
    created_at: new Date().toISOString(),
    company_name: "Norte Fit Studio",
    domain_root: "nortefit.com.br",
    city: "Sao Paulo",
    icp: "academia",
    ad_source: "meta",
    ad_active: true,
    contact_name: "Marina",
    contact_whatsapp: "+55 11 99999-0000",
    whatsapp_detected: true,
    pagespeed_mobile: 78,
    has_pixel: true,
    has_crm: true,
    crm_name: "HubSpot",
    fit_score: 45,
    timing_score: 46,
    total_score: 91,
    msg_whatsapp:
      "Oi Marina, vi que a Norte Fit esta com anuncio ativo e WhatsApp visivel. Tenho uma ideia simples para transformar essas conversas em mais alunos sem aumentar o time comercial.",
    msg_followup_d3: "Oi Marina, passando aqui de novo. Posso te mostrar em 10 minutos onde voces estao perdendo alunos no WhatsApp?",
    msg_followup_d7: "Ultima tentativa por aqui, Marina. Se fizer sentido, te mando um diagnostico rapido da captacao da Norte Fit.",
    audit_points: [
      {
        problem: "WhatsApp recebe trafego, mas nao ha triagem clara.",
        impact: "Leads quentes podem esfriar antes do primeiro atendimento.",
        recommendation: "Priorizar respostas por origem da campanha e intencao."
      }
    ],
    status: "awaiting_approval"
  },
  {
    id: "demo-2",
    created_at: new Date().toISOString(),
    company_name: "Clinica Aurora",
    domain_root: "clinicaaurora.com.br",
    city: "Campinas",
    icp: "clinica",
    ad_source: "google",
    whatsapp_detected: true,
    pagespeed_mobile: 63,
    has_pixel: false,
    has_crm: true,
    crm_name: "Pipedrive",
    fit_score: 42,
    timing_score: 42,
    total_score: 84,
    msg_whatsapp:
      "Oi, notei que a Clinica Aurora centraliza agendamentos no WhatsApp. Posso te mostrar um fluxo para responder mais rapido e separar pacientes com maior intencao?",
    status: "awaiting_approval"
  },
  {
    id: "demo-3",
    created_at: new Date().toISOString(),
    company_name: "Massa & Brasa",
    domain_root: "massaebrasa.com.br",
    city: "Rio de Janeiro",
    icp: "restaurante",
    ad_source: "meta",
    ad_active: true,
    whatsapp_detected: true,
    pagespeed_mobile: 52,
    has_pixel: true,
    has_crm: false,
    fit_score: 37,
    timing_score: 38,
    total_score: 75,
    msg_whatsapp:
      "Oi, vi que o Massa & Brasa usa WhatsApp para pedidos e tem campanhas ativas. Tenho uma abordagem para recuperar conversas paradas e medir retorno por canal.",
    status: "awaiting_approval"
  },
  {
    id: "demo-sent-1",
    created_at: new Date().toISOString(),
    company_name: "Oral Prime",
    domain_root: "oralprime.com.br",
    city: "Curitiba",
    icp: "clinica",
    ad_source: "meta",
    outreach_sent_at: new Date().toISOString(),
    outreach_channel: "whatsapp",
    response_type: "waiting",
    followup_d3_sent: true,
    followup_d7_sent: false,
    whatsapp_detected: true,
    pagespeed_mobile: 71,
    has_pixel: true,
    has_crm: true,
    crm_name: "RD Station",
    fit_score: 43,
    timing_score: 39,
    total_score: 82,
    msg_whatsapp:
      "Oi, vi que a Oral Prime esta levando trafego para WhatsApp. Posso te mostrar um ponto rapido para separar pacientes prontos para agendar?",
    msg_email_subject: "Triagem de pacientes da Oral Prime",
    msg_followup_d3: "Passando de novo. O maior gargalo parece estar entre clique e primeira resposta no WhatsApp.",
    msg_followup_d7: "Posso te mandar um ponto de auditoria sobre a captacao da Oral Prime?",
    status: "sent"
  },
  {
    id: "demo-sent-2",
    created_at: new Date().toISOString(),
    company_name: "Bella Shop",
    domain_root: "bellashop.com.br",
    city: "Belo Horizonte",
    icp: "ecommerce",
    ad_source: "google",
    outreach_sent_at: new Date().toISOString(),
    outreach_channel: "email",
    response_type: "positive",
    objection: "Pediu diagnostico na proxima semana.",
    followup_d3_sent: true,
    followup_d7_sent: true,
    meeting_scheduled: true,
    whatsapp_detected: false,
    pagespeed_mobile: 66,
    has_pixel: true,
    has_crm: true,
    crm_name: "HubSpot",
    fit_score: 41,
    timing_score: 34,
    total_score: 75,
    msg_whatsapp:
      "Vi que a Bella Shop tem campanhas ativas e stack de CRM. Posso mostrar onde a loja pode recuperar carrinhos e conversas paradas?",
    msg_email_subject: "Recuperacao de carrinhos na Bella Shop",
    msg_followup_d3: "Outro angulo: voces podem priorizar leads por produto visitado e origem da campanha.",
    msg_followup_d7: "Posso enviar um ponto de auditoria da jornada de compra da Bella Shop.",
    status: "sent"
  }
];
